sudo: false
language: scala
scala:
  - 2.12.4
jdk:
  - oraclejdk8
script:
  - sbt assembly
  - cp target/scala-*/*.jar .
cache:
  directories:
    - "$HOME/.ivy2"
    - "$HOME/.sbt"
addons:
  apt:
    packages:
    - oracle-java8-installer
